//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swellow.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Episodes()
        {
            this.CDs = new HashSet<CDs>();
        }
    
        public int Id { get; set; }
        public int No { get; set; }
        public string Title { get; set; }
        public string Display { get; set; }
        public string Plot { get; set; }
        public System.DateTime Date { get; set; }
        public bool HasResourse { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDs> CDs { get; set; }
        public virtual Seasons Seasons { get; set; }
    }
}
