//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swellow.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.CDs = new HashSet<CDs>();
        }
    
        public int Id { get; set; }
        public int Type { get; set; }
        public Nullable<int> Runtime { get; set; }
        public Nullable<int> Year { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> Score { get; set; }
        public Nullable<int> WorkId { get; set; }
        public string Display { get; set; }
        public string Name { get; set; }
        public string Outline { get; set; }
        public string Region { get; set; }
        public string DoubanId { get; set; }
        public string TmdbId { get; set; }
        public string ImdbId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDs> CDs { get; set; }
        public virtual Works Works { get; set; }
    }
}
