//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swellow.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casts> Casts { get; set; }
        public virtual DbSet<CDs> CDs { get; set; }
        public virtual DbSet<Companys> Companys { get; set; }
        public virtual DbSet<Episodes> Episodes { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Librarys> Librarys { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<Serieses> Serieses { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<VideoFolder> VideoFolder { get; set; }
        public virtual DbSet<WorkCasts> WorkCasts { get; set; }
        public virtual DbSet<WorkCompanys> WorkCompanys { get; set; }
        public virtual DbSet<Works> Works { get; set; }
    }
}
